
services:
  
  redis:
    image: "redis:alpine"
    depends_on:
      - db
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avitobootcamp
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d avitobootcamp" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080" 
    command: ["./main"]

